import { SessionProvider } from 'next-auth/react';
import type { Metadata } from 'next';
import Link from 'next/link';
import { ReactNode } from 'react';
import { auth } from '@/lib/auth';
import { ThemeProvider } from '@/components/theme-provider';
import { ModeToggle } from '@/components/ui/mode-toggle';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang='en' suppressHydrationWarning>
      <body className='antialiased m-5='>
        <SessionProvider session={session}>
          <ThemeProvider
            attribute='class'
            defaultTheme='system'
            enableSystem
            disableTransitionOnChange
          >
            <div className='flex gap-3 dark:gap-5'>
              <Link href='/' className='dark:text-red-500'>
                Home
              </Link>
              <Link href='/hello'>Hello</Link>
              <Link href='/hi'>Hi</Link>
              <Link href='/hi/night'>Hi Night</Link>
              <Link href='/parallel'>Parallel</Link>
              <Link href='/intercept'>Intercept</Link>
              <Link href='/photos'>Photos</Link>
              <Link href='/todos'>Todos</Link>
              <ModeToggle />
            </div>

            {children}

            <hr />
            <h2>Footer</h2>
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
