@baseUrl=http://localhost:8081

### login - success
POST {{baseUrl}}/api/subscriber/login
Content-Type: application/x-www-form-urlencoded

username = sample@gmail.com &
password = pwd00

> {%
    client.global.set("auth_token", response.body.accessToken);
    client.global.set("refresh_token", response.body.refreshToken);
%}

### refresh token
GET {{baseUrl}}/api/subscriber/refresh?refreshToken={{refresh_token}}
Authorization: Bearer {{auth_token}}

> {%
    client.global.set("auth_token", response.body.accessToken);
    client.global.set("refresh_token", response.body.refreshToken);
%}


### token valid test
GET {{baseUrl}}/members
Authorization: Bearer {{auth_token}}

### token valid test
GET {{baseUrl}}/members/2
Authorization: Bearer {{auth_token}}

## login - failure
POST {{baseUrl}}/api/subscriber/login
Content-Type: application/x-www-form-urlencoded

username = sample@gmail.com &
password = pwd00x

### textbook
POST {{baseUrl}}/api/subscriber/login?username=sample@gmail.com&password=pwd00
#Content-Type: application/x-www-form-urlencoded

### langs
GET {{baseUrl}}/api/public/langs

### set - langs
POST {{baseUrl}}/api/public/setlang
Content-Type: application/json
Accept-Language: zh